### ISSUE TITLE
Tests for Aequitas function

### ISSUE THREAD

**Issue by kammitama5** [pdaian/mevsimulator#1]
Input : N lists of transaction input orderings (see notes)
Output: List of transaction orderings (fair ordering)
3 tests should be fine?

- Should match expected transaction ordering
- Should work even if the graph is not complete
  - [x] Graph 2 
  - [X] Graph 3

- Should work even if the graph is cyclic(Condorcet paradox can cause cycles, therefore to retrieve a total ordering from the graph we look at the condensation graph)
   - [X] Graph 3
- Edge cases (empty graph, below the threshold specified by ```gamma```).
- Sorting for common descendant and not enough information for no common descendant

**Comment by gengmoqi** [comment]
Sounds good. Let me draw up additional test cases and add them to the notes

**Comment by gengmoqi** [comment]
Just [added a test case](https://github.com/pdaian/mevsimulator/commit/10c173f85e1ea10e0a5b383fb8277e1792dafbf3) for a graph with cycles, let me know if there's issues with this example
